### ISSUE TITLE
Do not work with OCS Inventory Plugin on GLPI 9.4.0

### ISSUE THREAD

**Issue by indication** [indication/docker-glpi-ocsinventory#1]
794c6791f97d7a2a4224b8f97e681a25a9828caa is not work  OCS Inventory Plugin on GLPI 9.4.0

Related to https://github.com/pluginsGLPI/ocsinventoryng/issues/199 (OCS Inventory Plugin)

**Comment by jackadam1981** [comment]
what  is the problem?

**Comment by indication** [comment]
![image](https://user-images.githubusercontent.com/47577/53338314-b6dde480-3946-11e9-8ed4-6e01c3e7699c.png)
OCS Inventory NG plugin (1.5.6) shows "This plugin requires GLPI >= 9.3".

**Comment by indication** [comment]
Upstram released 1.6.0.

**Comment by jackadam1981** [comment]
There aren’t any releases here

Releases are powered by tagging specific points of history in a repository. They’re great for marking release points like v1.0.

**Comment by indication** [comment]
Created tags: aggregated-11.9.0
Also, glpi , ocsinventory are tagged.
